import type { StaticImageData } from 'next/image'
import callsShot from '../../../public/paid-advertising/calls.webp'
import dashboardShot from '../../../public/paid-advertising/dashboard.webp'
import refundShot from '../../../public/paid-advertising/refund.webp'
import websiteShot from '../../../public/paid-advertising/website.webp'
import type { MediaDoc, PaidContent } from '@/lib/types'

// Fallback for the Pages 'paid-advertising' doc, block by block — same contract as mock/home.ts, and
// the same reason: the page prerenders at build time, so an empty or unreachable database has to
// render rather than fail the build. Kept byte-identical to what scripts/seed-paid.ts writes, so the
// CMS swap is verifiable by diffing the rendered page.
const toMedia = (img: StaticImageData, alt: string): MediaDoc => ({
  url: img.src,
  width: img.width,
  height: img.height,
  blurDataURL: img.blurDataURL,
  alt,
})

export const paid: PaidContent = {
  hero: {
    label: 'Pay Per Performance',
    heading: 'You only pay when we deliver.',
    pills: ['Google Ads', 'Microsoft Ads', 'Tik Tok Ads', 'Meta Ads'],
    description: {
      before:
        'We build your website, run your ads, handle your calls, filter your leads, and only send you the ones worth signing. ',
      // the designer set this phrase in Neue Haas bold at 24 against the 28px serif — a deliberate
      // voice change mid-sentence, hence its own field
      emphasis: 'You pay per qualified lead',
      after: '. If we don’t deliver in 6 months, you get your setup fee back.',
    },
    button: { label: 'LET’S BEGIN' },
  },
  guarantee: {
    // the break is authored — the designer set two lines, it is not a wrap
    body: 'Zero leads in 6 months?\nFull refund. No questions asked.',
    scratchLabel: 'Scratch To Reveal',
  },
  whatYouGet: {
    label: 'What You Get',
    heading: 'Everything built, managed, and filtered for you.',
    // Layout order: wide, the pair, wide. The page indexes these four slots directly.
    panels: [
      {
        title: 'A brand new website, built to convert.',
        body: 'Included in your setup fee. We design and develop a conversion-optimized website from scratch: fast, mobile-first, and engineered specifically to turn ad clicks into phone calls and form submissions. No templates. No DIY builders. A custom site built for your practice.',
        image: toMedia(websiteShot, 'Preview of a conversion-optimised landing page'),
      },
      {
        title: 'We answer every call and filter every lead.',
        body: 'Our team handles every inbound call and form submission generated by your campaigns. We qualify each one using criteria we define together at onboarding. Junk calls, tire kickers, wrong practice area? We filter them out. You only hear from leads worth your time.',
        image: toMedia(callsShot, 'Call attribution breakdown and total call count widgets'),
      },
      {
        title: 'A real-time dashboard to track, dispute, and pay as you go.',
        body: "No surprise invoices. Your dashboard shows every lead as it comes in, with full transparency. See your lead count, review details, dispute any lead you disagree with, and pay throughout the month. You're always in control of what you owe.",
        image: toMedia(dashboardShot, 'Lead dashboard showing call volume over time'),
      },
      {
        title: 'Money-back guarantee. Zero risk.',
        body: "If we don't generate a single qualified lead within 6 months of campaign launch, your $20,000 setup fee is refunded in full. You maintain your minimum ad spend, we do the rest. If it doesn't work, you walk away whole.",
        image: toMedia(refundShot, 'Full refund card marked zero risk'),
      },
    ],
  },
  results: {
    label: 'Results',
    heading: 'The numbers speak.',
    // The \n is the designer's break, not a wrap — desktop only, mobile lets the copy wrap.
    stats: [
      { value: '31', label: 'Qualified leads generated in a\nsingle month for one client' },
      { value: '$0', label: "What you owe\nif we don't deliver in 6 months" },
      { value: '100%', label: 'Of our revenue\ntied to your results' },
    ],
  },
  pricing: {
    label: 'Pricing',
    // the break after "Transparent." is authored, not a wrap
    heading: 'Simple. Transparent.\nPerformance-based.',
    tiers: [
      {
        label: 'One-time Setup',
        price: '$20,000',
        items: [
          'Business audit',
          'Custom Scaling Roadmap',
          'Full Website Build',
          'Campaign Architecture',
          'Tracking Infrastructure',
          'Call Handling Setup',
          'Reporting Dashboard',
        ],
      },
      {
        label: 'Per Qualified Lead',
        price: '$1,500',
        badge: 'PAY AS THEY COME IN',
        items: [
          'Only qualified leads that pass our filter and match the criteria we agreed on.',
          'You review every lead in your dashboard.',
          'Dispute any you disagree with.',
          'Pay as they come in.',
        ],
      },
    ],
    cta: { label: 'BOOK A CALL' },
  },
  faq: {
    label: 'FAQ',
    heading: 'Frequently Asked Questions',
    // ponytail: the Figma FAQ is five lorem rows with one lorem answer — the copy has not been
    // written. Shipped verbatim rather than invented, so nobody mistakes filler for approved copy.
    items: Array.from({ length: 5 }, () => ({
      question: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit?',
      answer: 'This is subtext which appears after expanding the accordion.',
    })),
  },
  note: {
    // the break after "have" is the design's — 458px is Figma's text width
    body: 'You have revenue from ads. Now build the brand that makes every future dollar cheaper to acquire.',
  },
}
