/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Admin-panel label only. Not rendered.
   */
  title: string;
  /**
   * The route. The home page is 'home'; every other doc is served at /<slug> — 'paid-advertising' is the one that exists.
   */
  slug: string;
  /**
   * Pages render these by type, not by the order below — section order is fixed in code, so dragging rows here changes nothing on the site. Deleting a row does: that section falls back to its placeholder copy. The list offers every block in the project; each page only reads the ones it renders (Hero/Who We Are/Strategy/About/Contact/Note on home, Paid Hero/Guarantee/What You Get/Results/Pricing/FAQ/Note on paid-advertising).
   */
  content: (
    | HeroBlock
    | WhoWeAreBlock
    | StrategyBlock
    | AboutBlock
    | ContactBlock
    | NoteBlock
    | PaidHeroBlock
    | GuaranteeBlock
    | WhatYouGetBlock
    | ResultsBlock
    | PricingBlock
    | FaqBlock
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Press Enter for the authored line break. Hero.tsx splits on the newline into hard-broken lines — this must stay a textarea, never richText.
   */
  heading: string;
  /**
   * No line breaks — body copy wraps to the viewport.
   */
  description: string;
  button: {
    label: string;
    /**
     * Leave empty to render an inert button (no destination yet).
     */
    href?: string | null;
  };
  /**
   * Marquee strip. Order is left-to-right and drives the fade stagger. Any aspect ratio — slides are fixed-height / auto-width.
   */
  slides: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhoWeAreBlock".
 */
export interface WhoWeAreBlock {
  /**
   * Bare text, e.g. "Who we are". The [ brackets ] and the uppercasing are CSS — do not type them.
   */
  label: string;
  /**
   * Press Enter for the authored line break.
   */
  heading: string;
  /**
   * Leave a BLANK line between paragraphs — that is the paragraph break. A single newline does nothing, and a trailing one is trimmed.
   */
  description: string;
  /**
   * Case studies, stacked in this order.
   */
  cards: {
    title: string;
    /**
     * Also the poster frame when a video is set.
     */
    image: string | Media;
    /**
     * Optional looping clip (mp4/webm) that replaces the still. Autoplays muted and downloads in full on mobile — keep it short and small.
     */
    video?: (string | null) | Media;
    body: string;
    stat: {
      /**
       * e.g. "133%". The number counts up on scroll-in.
       */
      value: string;
      /**
       * Press Enter for the two-line break (desktop only).
       */
      label: string;
    };
    link: {
      label: string;
      /**
       * Leave empty to render an inert button (no destination yet).
       */
      href?: string | null;
    };
    /**
     * Card ground, keyline and ink together. The hexes live in src/lib/palettes.ts.
     */
    palette: 'olive' | 'lilac';
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'whoWeAre';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StrategyBlock".
 */
export interface StrategyBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are CSS.
   */
  label: string;
  /**
   * Press Enter for an authored line break.
   */
  heading: string;
  /**
   * One paragraph — it wraps to the column on its own.
   */
  description: string;
  cards: {
    /**
     * Press Enter for the break — the subject always lands on line 2.
     */
    title: string;
    /**
     * Capability pills. The star tint comes from the row position, not from here — all three cards share one accent trio.
     */
    badges: {
      label: string;
      id?: string | null;
    }[];
    /**
     * The "if you..." sentence. Press Enter for a hard break — these are set by hand, not wrapped.
     */
    hook: string;
    /**
     * Only fill this in when the mobile breaks differ from desktop. Empty = hook is used at every width.
     */
    hookMobile?: string | null;
    /**
     * The explainer at the foot of the card. Line breaks render as spaces.
     */
    body: string;
    link: {
      label: string;
      /**
       * Leave empty to render an inert button (no destination yet).
       */
      href?: string | null;
    };
    /**
     * Tints the title and the card’s hover glow.
     */
    accent: 'lilac' | 'amber' | 'olive';
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'strategy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are CSS.
   */
  label: string;
  /**
   * Press Enter for the authored line break.
   */
  heading: string;
  /**
   * Two lines under the heading — press Enter after "nurture" for the break. At 24px the whole sentence fits one row, so it will not wrap on its own.
   */
  description: string;
  /**
   * Carousel order, left to right.
   */
  members: {
    /**
     * Landscape crop, shown at md and up. Optional — the carousel renders an empty frame while a headshot is missing.
     */
    photo?: (string | null) | Media;
    /**
     * Portrait crop, shown below md. The frame flips from 112:75 landscape to a 430px-tall column, so one file cannot serve both. Optional — falls back to the landscape crop, which centre-crops hard on a phone.
     */
    photoMobile?: (string | null) | Media;
    name: string;
    /**
     * The info-bar line. Press Enter for the authored two-line break.
     */
    role: string;
    id?: string | null;
  }[];
  story: {
    label: string;
    /**
     * Leave empty to render an inert button (no destination yet).
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are CSS.
   */
  label: string;
  /**
   * Display type, typed out on scroll-in. Press Enter for each authored line — this one is set at 200px, so the breaks are the design.
   */
  heading: string;
  /**
   * Exactly two: the first renders filled, the second outlined.
   */
  buttons: {
    label: string;
    /**
     * Leave empty to render an inert button.
     */
    href?: string | null;
    id?: string | null;
  }[];
  /**
   * Icon row. The platform picks the icon — there is no custom-icon path.
   */
  socials?:
    | {
        platform: 'instagram' | 'tiktok' | 'youtube' | 'facebook';
        /**
         * The account URL. Empty links to # until the real one exists.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Portrait crop, shown at md and up.
   */
  photo: string | Media;
  /**
   * Landscape crop, shown below md. The frame’s aspect flips, so one file cannot serve both.
   */
  photoMobile: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NoteBlock".
 */
export interface NoteBlock {
  /**
   * Rendered with whitespace-pre-line, so every Enter you press is a real line break. The design puts the closing sentence on its own row.
   */
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'note';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PaidHeroBlock".
 */
export interface PaidHeroBlock {
  /**
   * Bare text, e.g. "Pay Per Performance".
   */
  label: string;
  /**
   * One line at desktop; on a phone it breaks itself at the text width.
   */
  heading: string;
  /**
   * Ad platforms. The star colour comes from the row position, not from here — four rows fill the design’s trio-plus-one.
   */
  pills: {
    label: string;
    id?: string | null;
  }[];
  /**
   * One sentence set in three parts: the middle one is the bold Neue Haas run the designer put mid-sentence. Mind the spaces and the full stop at the joins.
   */
  description: {
    before: string;
    /**
     * Rendered bold and a size down, e.g. "You pay per qualified lead".
     */
    emphasis: string;
    /**
     * Starts with the punctuation that closes the emphasised phrase.
     */
    after: string;
  };
  button: {
    label: string;
    /**
     * Leave empty to render an inert button (no destination yet).
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'paidHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GuaranteeBlock".
 */
export interface GuaranteeBlock {
  /**
   * Press Enter for the authored break — the designer set two lines.
   */
  body: string;
  /**
   * Printed on the panel covering the copy above. Never seen under reduced motion, where the cover is not drawn at all.
   */
  scratchLabel: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'guarantee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatYouGetBlock".
 */
export interface WhatYouGetBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are added by the page.
   */
  label: string;
  /**
   * Wraps to the column on its own — no authored break.
   */
  heading: string;
  /**
   * Exactly four, in layout order: wide, then the two side by side, then wide again. Row 1 and row 4 put their mock beside the copy; rows 2 and 3 put it underneath.
   */
  panels: {
    title: string;
    body: string;
    /**
     * Flat export of the product mock (2x webp). Not a live widget — replacing this file is how the artwork changes.
     */
    image: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'whatYouGet';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsBlock".
 */
export interface ResultsBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are added by the page.
   */
  label: string;
  heading: string;
  /**
   * Cards, left to right. They fade in in this order.
   */
  stats: {
    /**
     * The big number, e.g. "31" or "$0". Free text — not counted up.
     */
    value: string;
    /**
     * Press Enter for the desktop break. On a phone the same copy wraps instead.
     */
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'results';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are added by the page.
   */
  label: string;
  /**
   * Press Enter for the authored break after the second sentence.
   */
  heading: string;
  tiers: {
    /**
     * e.g. "One-time Setup".
     */
    label: string;
    price: string;
    /**
     * The tab straddling the card’s top edge. Filling this in also gives the card the brand keyline and glow — leave it empty for the plain card.
     */
    badge?: string | null;
    /**
     * Bulleted list.
     */
    items: {
      label: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  cta: {
    label: string;
    /**
     * Leave empty to render an inert button (no destination yet).
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  /**
   * Bare text. The [ brackets ] and uppercasing are added by the page.
   */
  label: string;
  heading: string;
  /**
   * Rows, top to bottom. Each opens on click and slides shut again.
   */
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        whoWeAre?: T | WhoWeAreBlockSelect<T>;
        strategy?: T | StrategyBlockSelect<T>;
        about?: T | AboutBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        note?: T | NoteBlockSelect<T>;
        paidHero?: T | PaidHeroBlockSelect<T>;
        guarantee?: T | GuaranteeBlockSelect<T>;
        whatYouGet?: T | WhatYouGetBlockSelect<T>;
        results?: T | ResultsBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  slides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhoWeAreBlock_select".
 */
export interface WhoWeAreBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        image?: T;
        video?: T;
        body?: T;
        stat?:
          | T
          | {
              value?: T;
              label?: T;
            };
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        palette?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StrategyBlock_select".
 */
export interface StrategyBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        badges?:
          | T
          | {
              label?: T;
              id?: T;
            };
        hook?: T;
        hookMobile?: T;
        body?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        accent?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  description?: T;
  members?:
    | T
    | {
        photo?: T;
        photoMobile?: T;
        name?: T;
        role?: T;
        id?: T;
      };
  story?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  buttons?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  photo?: T;
  photoMobile?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NoteBlock_select".
 */
export interface NoteBlockSelect<T extends boolean = true> {
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PaidHeroBlock_select".
 */
export interface PaidHeroBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  pills?:
    | T
    | {
        label?: T;
        id?: T;
      };
  description?:
    | T
    | {
        before?: T;
        emphasis?: T;
        after?: T;
      };
  button?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GuaranteeBlock_select".
 */
export interface GuaranteeBlockSelect<T extends boolean = true> {
  body?: T;
  scratchLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatYouGetBlock_select".
 */
export interface WhatYouGetBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  panels?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsBlock_select".
 */
export interface ResultsBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  tiers?:
    | T
    | {
        label?: T;
        price?: T;
        badge?: T;
        items?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}